global:
envs:
    PING_IDENTITY_ACCEPT_EULA: "YES"
ingress:
    enabled: true
    addReleaseNameToHost: prepend
    defaultDomain: "insert domain name here"
    defaultTlsSecret:
    annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        kubernetes.io/ingress.class: "nginx-public"

#############################################################
# pingaccess-admin values
#############################################################
pingaccess-admin:
enabled: true
privateCert:
    generate: true
envs: 
    PING_IDENTITY_PASSWORD: "2FederateM0re!"

#############################################################
# pingaccess-engine values
#############################################################
pingaccess-engine:
enabled: true
container:
    replicaCount: 1
envs: 
    PING_IDENTITY_PASSWORD: "2FederateM0re!"
